ARG IMAGE_TYPE="gpu"
FROM gcr.io/kubeflow-images-public/tensorflow-2.1.0-notebook-gpu:1.0.0
USER root
RUN pip3 install tensorflow_datasets

COPY krb5cc_1000 /tmp/krb5cc_0
COPY custom-code.py

USER jovyan
