apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "tfjob-custom"
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            command:
              - "python"
              - "/multy_worker.py"
            image: registry.hub.docker.com/dejangolubovic/tfjob-test
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              limits:
                nvidia.com/gpu: 1
            workingDir: /
          restartPolicy: OnFailure
    Worker:
      replicas: 4
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            command:
              - "python"
              - "/multy_worker.py"
            image: registry.hub.docker.com/dejangolubovic/tfjob-test
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              limits:
                nvidia.com/gpu: 1
            workingDir: /
          restartPolicy: OnFailure
